from toolkit.template import TEMPLATE_SCAFFOLD_PROJECT_PATH

TEMPLATE_PATH = TEMPLATE_SCAFFOLD_PROJECT_PATH


TEMPLATE_ANSIBLE_PATH = TEMPLATE_PATH / "ansible"
TEMPLATE_CLANG_PATH = TEMPLATE_PATH / "clang"
TEMPLATE_CPP_PATH = TEMPLATE_PATH / "cpp"
TEMPLATE_CPP_QT5_PATH = TEMPLATE_CPP_PATH / "qt5"
TEMPLATE_EXAMPLE_PATH = TEMPLATE_PATH / "example"
TEMPLATE_DOCKER_PATH = TEMPLATE_PATH / "docker"
TEMPLATE_GOLANG_PATH = TEMPLATE_PATH / "golang"
TEMPLATE_NOTES_PATH = TEMPLATE_PATH / "notes"
TEMPLATE_PYTHON_PATH = TEMPLATE_PATH / "python"
