from pathlib import Path

TEMPLATE_PATH = Path(__file__).parent

TEMPLATE_SCAFFOLD_PATH = TEMPLATE_PATH / "scaffold"

TEMPLATE_SCAFFOLD_CONFIG_PATH = TEMPLATE_SCAFFOLD_PATH / "config"

TEMPLATE_SCAFFOLD_PROJECT_PATH = TEMPLATE_SCAFFOLD_PATH / "project"
