syntax on
set showmode
set showcmd
set encoding=utf-8
filetype indent on
set autoindent
set shiftwidth=2
set tabstop=2
set expandtab
set softtabstop=2
set number
set cursorline
set textwidth=80
set wrap
set linebreak
set wrapmargin=2
set scrolloff=5
set sidescrolloff=15
set laststatus=2
set showmatch
set hlsearch
set incsearch
set ignorecase
set history=1000
set wildmenu
set wildmode=longest:list,full
