{{SLASH_COMMENTS}}

#ifndef {{APP_NAME_UPPER}}__VERSION_H
#define {{APP_NAME_UPPER}}__VERSION_H

#define BUILD_TIMESTAMP "@BUILD_TIMESTAMP@"

#define VERSION_MAJOR @VERSION_MAJOR@
#define VERSION_MINOR @VERSION_MINOR@
#define VERSION_PATCH @VERSION_PATCH@
#define APP_VERSION "@APP_VERSION@"

#define GIT_BRANCH_NAME "@GIT_BRANCH_NAME@"
#define GIT_COMMIT_HASH "@GIT_COMMIT_HASH@"

#define APP_VERSION_WITH_BUILD_INFO "@APP_VERSION_WITH_BUILD_INFO@"

#endif//{{APP_NAME_UPPER}}__VERSION_H
